# .github/workflows/ci.yml
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install project deps if you have requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run basic check
        run: |
          echo "Build successful"
          # optional: run a small python check to ensure files import
          python -c "import sys; print('Python', sys.version.split()[0])"